fixes:
  # - "before/::after/"  # move path   e.g., "before/path" => "after/path"
  # - "::after/"         # move root   e.g., "path/" => "after/path/"
  - "htool/::" # reduce root e.g., "before/path/" => "path/"
